--- #YAML:1.0
name: CGI-Application-Plugin-Apache
version: 0.10
author:
  - Michael Peters <mpeters@plusthree.com>
abstract: Allow CGI::Application to use Apache::* modules without interference
license: perl
generated_by: Module::Build version 0.2604, without YAML.pm
